a=input("Insert the value of first integer ")
b=input("Insert the value of first integer ")
print(int(a)+int(b))
print(int(a)-int(b))
print(int(a)*int(b))
print(int(a)/int(b))
print(int(a)//int(b))
print(int(a)%int(b))
print(int(a)**int(b))